language: rust

sudo: required  # workaround to allow code coverage (see https://github.com/travis-ci/travis-ci/issues/9061)
dist: trusty

rust:
  - stable
  - beta
  - nightly
  
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
after_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

cache: cargo

# Taken from Trust
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

addons:
  apt:
    packages:
      - libssl-dev

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
