language: rust

rust:
  - stable

script:
  - cargo build -p forester
  - cargo test -p forester
  - cargo build -p forester --release
  - cargo test -p forester --release

cache: cargo

# Taken from Trust
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
