[package]
name = "examples-common"
version = "0.1.0"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]

[dependencies]
forester = { path = "../forester-crate"  }
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
