[package]
name = "forester-benchmarks"
version = "0.0.1"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]
publish = false  # prevent publication by mistake

[dev-dependencies]
forester = { path = "../forester" }
criterion = "0.2"
rand = "0.4"


[[bench]]
name = "benchmark"
harness = false
